config/routes.rb
Rails.application.routes.draw do
  resources :tiles

  root 'board#index'

end

app/models/tile.rb
class Tile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def index
    @tiles = Tile.all
  end
end

app/controllers/tiles_controller.rb
class TilesController < ApplicationController
  before_action :set_tile, only: [:show, :edit, :update, :destroy]

  # GET /tiles
  # GET /tiles.json
  def index
    @tiles = Tile.all
  end

  # GET /tiles/1
  # GET /tiles/1.json
  def show
  end

  # GET /tiles/new
  def new
    @tile = Tile.new
  end

  # GET /tiles/1/edit
  def edit
  end

  # POST /tiles
  # POST /tiles.json
  def create
    @tile = Tile.new(tile_params)

    respond_to do |format|
      if @tile.save
        format.html { redirect_to @tile, notice: 'Tile was successfully created.' }
        format.json { render :show, status: :created, location: @tile }
      else
        format.html { render :new }
        format.json { render json: @tile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tiles/1
  # PATCH/PUT /tiles/1.json
  def update
    respond_to do |format|
      if @tile.update(tile_params)
        format.html { redirect_to @tile, notice: 'Tile was successfully updated.' }
        format.json { render :show, status: :ok, location: @tile }
      else
        format.html { render :edit }
        format.json { render json: @tile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tiles/1
  # DELETE /tiles/1.json
  def destroy
    @tile.destroy
    respond_to do |format|
      format.html { redirect_to tiles_url, notice: 'Tile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tile
      @tile = Tile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tile_params
      params.require(:tile).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/tiles_helper.rb
module TilesHelper
end

app/views/board/index.html.erb
<p>Here is the board where tiles will be displayed. For now, see:
<a href="tiles/">Tiles index</a>
</p>

<script type="text/javascript">

  window.tiles = <%= @tiles.to_json.html_safe -%>
</script>

<p id="notice"><%= notice %></p>
<div id="tools_box">
  <input type="text" style="opacity:0;" disabled="disabled" value="" id="orInput">
  <input type="search" name="afficher" autocorrect="off" autocapitalize="none" value="" id="afficher">
  <input type="button" value="x" id="button_editmode">
  <!-- <input type="button" value="Paste" id="button_paste" exec="paste"> -->
  <input type="button" value="Save" id="button_save">
  <input type="button" value="✍" id="button_comment">
  <!-- <input type="button" value="⚓" id="button_newlink"> -->
  <input type="button" value="G" id="style_g" exec="bold">
  <input type="button" value="I" id="style_i" exec="italic">
  <input type="button" value="S" id="style_s" exec="underline">
  <!-- <input type="button" value="☤" id="style_sn"> -->
  <!-- <h2>Modifiés</h2>
  <ul id="unsavedList"></ul> -->
</div>

<div id="notes">
</div>

<div id="container">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pmwiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tiles/_form.html.erb
<%= form_for(@tile) do |f| %>
  <% if @tile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tile.errors.count, "error") %> prohibited this tile from being saved:</h2>

      <ul>
      <% @tile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tiles/edit.html.erb
<h1>Editing Tile</h1>

<%= render 'form' %>

<%= link_to 'Show', @tile %> |
<%= link_to 'Back', tiles_path %>

app/views/tiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tiles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tiles.each do |tile| %>
      <tr>
        <td><%= tile.title %></td>
        <td><%= tile.text.html_safe %></td>
        <td><%= link_to 'Show', tile %></td>
        <td><%= link_to 'Edit', edit_tile_path(tile) %></td>
        <td><%= link_to 'Destroy', tile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tile', new_tile_path %>

app/views/tiles/new.html.erb
<h1>New Tile</h1>

<%= render 'form' %>

<%= link_to 'Back', tiles_path %>

app/views/tiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tile.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @tile.text %>
</p>

<%= link_to 'Edit', edit_tile_path(@tile) %> |
<%= link_to 'Back', tiles_path %>